# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 740)
        MainWindow.setMaximumSize(QtCore.QSize(800, 800))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 0, 801, 701))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.camera_control = QtWidgets.QGroupBox(self.tab)
        self.camera_control.setGeometry(QtCore.QRect(430, 490, 291, 171))
        self.camera_control.setObjectName("camera_control")
        self.cam_up = QtWidgets.QPushButton(self.camera_control)
        self.cam_up.setGeometry(QtCore.QRect(50, 40, 51, 31))
        self.cam_up.setObjectName("cam_up")
        self.cam_down = QtWidgets.QPushButton(self.camera_control)
        self.cam_down.setGeometry(QtCore.QRect(50, 120, 51, 31))
        self.cam_down.setObjectName("cam_down")
        self.cam_left = QtWidgets.QPushButton(self.camera_control)
        self.cam_left.setGeometry(QtCore.QRect(10, 80, 51, 31))
        self.cam_left.setObjectName("cam_left")
        self.cam_right = QtWidgets.QPushButton(self.camera_control)
        self.cam_right.setGeometry(QtCore.QRect(90, 80, 51, 31))
        self.cam_right.setObjectName("cam_right")
        self.cam_set_zero = QtWidgets.QPushButton(self.camera_control)
        self.cam_set_zero.setGeometry(QtCore.QRect(160, 80, 113, 32))
        self.cam_set_zero.setObjectName("cam_set_zero")
        self.cam_go_zero = QtWidgets.QPushButton(self.camera_control)
        self.cam_go_zero.setGeometry(QtCore.QRect(160, 120, 113, 32))
        self.cam_go_zero.setObjectName("cam_go_zero")
        self.label_9 = QtWidgets.QLabel(self.camera_control)
        self.label_9.setGeometry(QtCore.QRect(150, 40, 71, 16))
        self.label_9.setObjectName("label_9")
        self.cam_pose = QtWidgets.QLabel(self.camera_control)
        self.cam_pose.setGeometry(QtCore.QRect(230, 40, 41, 16))
        self.cam_pose.setObjectName("cam_pose")
        self.measure = QtWidgets.QGroupBox(self.tab)
        self.measure.setGeometry(QtCore.QRect(30, 350, 321, 131))
        self.measure.setObjectName("measure")
        self.pushButton_13 = QtWidgets.QPushButton(self.measure)
        self.pushButton_13.setGeometry(QtCore.QRect(200, 60, 91, 31))
        self.pushButton_13.setObjectName("pushButton_13")
        self.location = QtWidgets.QLabel(self.measure)
        self.location.setGeometry(QtCore.QRect(280, 30, 31, 16))
        self.location.setObjectName("location")
        self.label_6 = QtWidgets.QLabel(self.measure)
        self.label_6.setGeometry(QtCore.QRect(210, 30, 60, 16))
        self.label_6.setObjectName("label_6")
        self.label_4 = QtWidgets.QLabel(self.measure)
        self.label_4.setGeometry(QtCore.QRect(10, 30, 60, 16))
        self.label_4.setObjectName("label_4")
        self.length = QtWidgets.QLabel(self.measure)
        self.length.setGeometry(QtCore.QRect(150, 30, 21, 16))
        self.length.setObjectName("length")
        self.width = QtWidgets.QLabel(self.measure)
        self.width.setGeometry(QtCore.QRect(60, 30, 21, 16))
        self.width.setObjectName("width")
        self.label_5 = QtWidgets.QLabel(self.measure)
        self.label_5.setGeometry(QtCore.QRect(110, 30, 60, 16))
        self.label_5.setObjectName("label_5")
        self.pushButton_14 = QtWidgets.QPushButton(self.measure)
        self.pushButton_14.setGeometry(QtCore.QRect(0, 60, 91, 31))
        self.pushButton_14.setObjectName("pushButton_14")
        self.pushButton_15 = QtWidgets.QPushButton(self.measure)
        self.pushButton_15.setGeometry(QtCore.QRect(100, 60, 81, 31))
        self.pushButton_15.setObjectName("pushButton_15")
        self.pushButton_16 = QtWidgets.QPushButton(self.measure)
        self.pushButton_16.setGeometry(QtCore.QRect(200, 100, 91, 31))
        self.pushButton_16.setObjectName("pushButton_16")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(430, 350, 341, 131))
        self.groupBox.setObjectName("groupBox")
        self.comboBox = QtWidgets.QComboBox(self.groupBox)
        self.comboBox.setGeometry(QtCore.QRect(80, 20, 104, 26))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(10, 30, 60, 16))
        self.label_8.setObjectName("label_8")
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setGeometry(QtCore.QRect(10, 60, 60, 16))
        self.label_10.setObjectName("label_10")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit.setGeometry(QtCore.QRect(80, 60, 113, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.comboBox_2 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_2.setGeometry(QtCore.QRect(80, 90, 104, 26))
        self.comboBox_2.setObjectName("comboBox_2")
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        self.label_11.setGeometry(QtCore.QRect(10, 90, 60, 16))
        self.label_11.setObjectName("label_11")
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setGeometry(QtCore.QRect(230, 90, 71, 31))
        self.pushButton.setObjectName("pushButton")
        self.checkBox = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox.setGeometry(QtCore.QRect(230, 30, 87, 20))
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_2.setGeometry(QtCore.QRect(230, 60, 87, 20))
        self.checkBox_2.setObjectName("checkBox_2")
        self.widget = QtWidgets.QWidget(self.tab)
        self.widget.setGeometry(QtCore.QRect(30, 50, 381, 281))
        self.widget.setObjectName("widget")
        self.graphicsView = PlotWidget(self.widget)
        self.graphicsView.setGeometry(QtCore.QRect(20, 10, 351, 251))
        self.graphicsView.setObjectName("graphicsView")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(180, 10, 91, 31))
        self.label.setObjectName("label")
        self.widget_3 = QtWidgets.QWidget(self.tab)
        self.widget_3.setGeometry(QtCore.QRect(430, 60, 331, 261))
        self.widget_3.setObjectName("widget_3")
        self.ptz_control = QtWidgets.QGroupBox(self.tab)
        self.ptz_control.setGeometry(QtCore.QRect(30, 490, 281, 171))
        self.ptz_control.setObjectName("ptz_control")
        self.ptz_up = QtWidgets.QPushButton(self.ptz_control)
        self.ptz_up.setGeometry(QtCore.QRect(50, 40, 51, 31))
        self.ptz_up.setObjectName("ptz_up")
        self.ptz_down = QtWidgets.QPushButton(self.ptz_control)
        self.ptz_down.setGeometry(QtCore.QRect(50, 120, 51, 31))
        self.ptz_down.setObjectName("ptz_down")
        self.ptz_left = QtWidgets.QPushButton(self.ptz_control)
        self.ptz_left.setGeometry(QtCore.QRect(10, 80, 51, 31))
        self.ptz_left.setObjectName("ptz_left")
        self.ptz_right = QtWidgets.QPushButton(self.ptz_control)
        self.ptz_right.setGeometry(QtCore.QRect(90, 80, 51, 31))
        self.ptz_right.setObjectName("ptz_right")
        self.ptz_set_zero = QtWidgets.QPushButton(self.ptz_control)
        self.ptz_set_zero.setGeometry(QtCore.QRect(160, 80, 113, 32))
        self.ptz_set_zero.setObjectName("ptz_set_zero")
        self.ptz_go_zeto = QtWidgets.QPushButton(self.ptz_control)
        self.ptz_go_zeto.setGeometry(QtCore.QRect(160, 120, 113, 32))
        self.ptz_go_zeto.setObjectName("ptz_go_zeto")
        self.label_7 = QtWidgets.QLabel(self.ptz_control)
        self.label_7.setGeometry(QtCore.QRect(160, 40, 60, 16))
        self.label_7.setObjectName("label_7")
        self.ptz_pose = QtWidgets.QLabel(self.ptz_control)
        self.ptz_pose.setGeometry(QtCore.QRect(230, 40, 60, 16))
        self.ptz_pose.setObjectName("ptz_pose")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(560, 10, 60, 16))
        self.label_3.setObjectName("label_3")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "雷达扫描系统"))
        self.camera_control.setTitle(_translate("MainWindow", "摄像头手动控制"))
        self.cam_up.setText(_translate("MainWindow", "上"))
        self.cam_down.setText(_translate("MainWindow", "下"))
        self.cam_left.setText(_translate("MainWindow", "左"))
        self.cam_right.setText(_translate("MainWindow", "右"))
        self.cam_set_zero.setText(_translate("MainWindow", "设置抓拍点"))
        self.cam_go_zero.setText(_translate("MainWindow", "移动至抓拍点"))
        self.label_9.setText(_translate("MainWindow", "摄像头位置:"))
        self.cam_pose.setText(_translate("MainWindow", "0,0"))
        self.measure.setTitle(_translate("MainWindow", "测量控制"))
        self.pushButton_13.setText(_translate("MainWindow", "位置测量"))
        self.location.setText(_translate("MainWindow", "0,0"))
        self.label_6.setText(_translate("MainWindow", "中心位置："))
        self.label_4.setText(_translate("MainWindow", "长度："))
        self.length.setText(_translate("MainWindow", "0"))
        self.width.setText(_translate("MainWindow", "0"))
        self.label_5.setText(_translate("MainWindow", "宽度："))
        self.pushButton_14.setText(_translate("MainWindow", "长度测量"))
        self.pushButton_15.setText(_translate("MainWindow", "宽度测量"))
        self.pushButton_16.setText(_translate("MainWindow", "自动测量"))
        self.groupBox.setTitle(_translate("MainWindow", "系统设置"))
        self.comboBox.setItemText(0, _translate("MainWindow", "自动"))
        self.comboBox.setItemText(1, _translate("MainWindow", "手动"))
        self.comboBox.setItemText(2, _translate("MainWindow", "校准"))
        self.label_8.setText(_translate("MainWindow", "模式选择:"))
        self.label_10.setText(_translate("MainWindow", "雷达地址:"))
        self.lineEdit.setText(_translate("MainWindow", "192.168.0.1"))
        self.label_11.setText(_translate("MainWindow", "云台串口:"))
        self.pushButton.setText(_translate("MainWindow", "启动"))
        self.checkBox.setText(_translate("MainWindow", "自启动"))
        self.checkBox_2.setText(_translate("MainWindow", "开启调试"))
        self.label.setText(_translate("MainWindow", "雷达三维扫描"))
        self.ptz_control.setTitle(_translate("MainWindow", "云台手动控制"))
        self.ptz_up.setText(_translate("MainWindow", "上"))
        self.ptz_down.setText(_translate("MainWindow", "下"))
        self.ptz_left.setText(_translate("MainWindow", "左"))
        self.ptz_right.setText(_translate("MainWindow", "右"))
        self.ptz_set_zero.setText(_translate("MainWindow", "设置校准点"))
        self.ptz_go_zeto.setText(_translate("MainWindow", "移动至校准点"))
        self.label_7.setText(_translate("MainWindow", "云台位置:"))
        self.ptz_pose.setText(_translate("MainWindow", "0,0"))
        self.label_3.setText(_translate("MainWindow", "监控画面"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Tab 1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))

from pyqtgraph import PlotWidget
